apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi
  namespace: argocd
spec:
  destination:
    namespace: staging
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/TreeKat71/my-k8s-challenge-manifests.git
    targetRevision: master
    path: fastapi
  syncPolicy: {}
