name: DigitalOcean Kubernetes Challenge

on:
  push:
    branches: ["master"]
  # Can be trigger manually
  workflow_dispatch:

jobs:
  manifests:
    runs-on: ubuntu-latest
    steps:
      # Get Codebase
      - uses: actions/checkout@v2
      # Setup python env
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      # Upgrade pip
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      # yaml lint can check earlier
      - name: Kubernetes yaml lint
        run: |
          pip install yamllint
          yamllint */*.yaml
